# Generated by Django 5.1.4 on 2026-03-05 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_status_change', models.BooleanField(default=True)),
                ('email_document_expiry', models.BooleanField(default=True)),
                ('email_vessel_arrived', models.BooleanField(default=True)),
                ('email_payment_due', models.BooleanField(default=True)),
                ('email_customs_alert', models.BooleanField(default=True)),
                ('whatsapp_status_change', models.BooleanField(default=False)),
                ('whatsapp_vessel_arrived', models.BooleanField(default=False)),
                ('whatsapp_payment_overdue', models.BooleanField(default=False)),
                ('document_expiry_alert_days', models.PositiveIntegerField(default=7, verbose_name='Alerter X jours avant expiration document')),
                ('payment_due_alert_days', models.PositiveIntegerField(default=3, verbose_name='Alerter X jours avant échéance paiement')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('status_change', 'Changement de statut'), ('document_expiry', 'Document bientôt expiré'), ('document_expired', 'Document expiré'), ('vessel_arrived', 'Navire arrivé au port'), ('payment_due', 'Échéance de paiement proche'), ('payment_overdue', 'Paiement en retard'), ('customs_alert', 'Alerte douanière'), ('system', 'Système')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipments.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx')],
            },
        ),
    ]
