# Generated by Django 5.1.4 on 2026-03-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du chauffeur')),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_position_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoints_passed', models.JSONField(blank=True, default=list)),
                ('tracking_active', models.BooleanField(default=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='road_tracking', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Tracking routier',
            },
        ),
        migrations.CreateModel(
            name='VesselTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=100, verbose_name='Nom du navire')),
                ('imo_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro IMO')),
                ('mmsi', models.CharField(blank=True, max_length=20, verbose_name='MMSI')),
                ('vessel_flag', models.CharField(blank=True, max_length=5)),
                ('bill_of_lading', models.CharField(blank=True, max_length=50, verbose_name='Connaissement (B/L)')),
                ('container_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de conteneur')),
                ('voyage_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de voyage')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_speed_knots', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('current_heading', models.IntegerField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50)),
                ('last_position_at', models.DateTimeField(blank=True, null=True)),
                ('vessel_eta', models.DateTimeField(blank=True, null=True, verbose_name='ETA navire (officielle)')),
                ('departure_port_code', models.CharField(blank=True, max_length=10)),
                ('arrival_port_code', models.CharField(blank=True, max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sync API')),
                ('tracking_active', models.BooleanField(default=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_tracking', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Tracking navire',
            },
        ),
        migrations.CreateModel(
            name='VesselPositionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_knots', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_logs', to='tracking.vesseltracking')),
            ],
            options={
                'verbose_name': 'Log de position navire',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vessel', 'recorded_at'], name='tracking_ve_vessel__86966f_idx')],
            },
        ),
    ]
