# Generated by Django 5.1.4 on 2026-03-05 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence dossier')),
                ('direction', models.CharField(choices=[('import', 'Importation'), ('export', 'Exportation'), ('transit', 'Transit')], max_length=10)),
                ('origin_country', models.CharField(max_length=100, verbose_name="Pays d'origine")),
                ('origin_port_or_city', models.CharField(max_length=100, verbose_name="Port / Ville d'origine")),
                ('destination_country', models.CharField(max_length=100, verbose_name='Pays de destination')),
                ('destination_port_or_city', models.CharField(max_length=100, verbose_name='Port / Ville de destination')),
                ('goods_description', models.TextField(verbose_name='Description des marchandises')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='Code HS')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('transport_mode', models.CharField(choices=[('sea', 'Maritime'), ('air', 'Aérien'), ('road', 'Routier'), ('multi', 'Multimodal')], max_length=10)),
                ('incoterm', models.CharField(blank=True, choices=[('EXW', 'EXW – Ex Works'), ('FCA', 'FCA – Free Carrier'), ('FAS', 'FAS – Free Alongside Ship'), ('FOB', 'FOB – Free On Board'), ('CFR', 'CFR – Cost and Freight'), ('CIF', 'CIF – Cost Insurance Freight'), ('CPT', 'CPT – Carriage Paid To'), ('CIP', 'CIP – Carriage and Insurance Paid'), ('DAP', 'DAP – Delivered At Place'), ('DPU', 'DPU – Delivered at Place Unloaded'), ('DDP', 'DDP – Delivered Duty Paid')], max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('booking', 'Réservation en cours'), ('goods_ready', 'Marchandises prêtes'), ('in_transit', 'En transit'), ('at_origin_port', "Au port d'origine"), ('on_vessel', 'En mer'), ('at_dest_port', 'Au port de destination'), ('customs', 'En dédouanement'), ('cleared', 'Dédouané'), ('out_for_delivery', 'En livraison finale'), ('delivered', 'Livré'), ('on_hold', 'Bloqué'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('estimated_departure', models.DateField(blank=True, null=True, verbose_name='Départ estimé (ETD)')),
                ('actual_departure', models.DateField(blank=True, null=True, verbose_name='Départ réel')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='Arrivée estimée (ETA)')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='Arrivée réelle')),
                ('customs_start', models.DateField(blank=True, null=True, verbose_name='Début dédouanement')),
                ('customs_end', models.DateField(blank=True, null=True, verbose_name='Fin dédouanement')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivée')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_shipments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('customs_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokered_shipments', to='partners.partner', verbose_name='Commissionnaire en douane')),
                ('freight_forwarder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_shipments', to='partners.partner', verbose_name='Transitaire')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='accounts.organisation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_shipments', to='partners.partner', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Expédition',
                'verbose_name_plural': 'Expéditions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('booking', 'Réservation en cours'), ('goods_ready', 'Marchandises prêtes'), ('in_transit', 'En transit'), ('at_origin_port', "Au port d'origine"), ('on_vessel', 'En mer'), ('at_dest_port', 'Au port de destination'), ('customs', 'En dédouanement'), ('cleared', 'Dédouané'), ('out_for_delivery', 'En livraison finale'), ('delivered', 'Livré'), ('on_hold', 'Bloqué'), ('cancelled', 'Annulé')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['organisation', 'status'], name='shipments_s_organis_c00ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['organisation', 'is_archived'], name='shipments_s_organis_4ee47d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['organisation', 'direction'], name='shipments_s_organis_8adfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['reference'], name='shipments_s_referen_5d8526_idx'),
        ),
    ]
