# Generated by Django 5.1.4 on 2026-03-05 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('partners', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDutySimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=20, verbose_name='Code HS')),
                ('goods_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur CIF (FCFA)')),
                ('transport_mode', models.CharField(max_length=10)),
                ('origin_country', models.CharField(max_length=100)),
                ('customs_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('duty_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_simulations', to='shipments.shipment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Simulation douanière',
                'verbose_name_plural': 'Simulations douanières',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('goods_value', 'Valeur marchandises'), ('freight', 'Fret'), ('insurance', 'Assurance'), ('customs_duties', 'Droits de douane'), ('vat', "TVA à l'import"), ('port_fees', 'Frais portuaires'), ('handling', 'Manutention'), ('scanning', 'Frais de scanning'), ('storage', 'Frais de magasinage'), ('transport_local', 'Transport local / livraison'), ('broker_fees', 'Honoraires transitaire / courtier'), ('other', 'Autre')], max_length=25)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='shipments.shipment')),
            ],
            options={
                'verbose_name': "Coût d'expédition",
                'verbose_name_plural': "Coûts d'expédition",
                'ordering': ['cost_type'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('method', models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('lc', 'Lettre de crédit (L/C)'), ('western_union', 'Western Union'), ('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('other', 'Autre')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence virement / reçu')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Date de paiement effectif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['shipment', 'status'], name='finance_pay_shipmen_5954c0_idx'), models.Index(fields=['due_date'], name='finance_pay_due_dat_3e278c_idx')],
            },
        ),
    ]
